---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      tags:
        - apt_get
      when:  ansible_os_family=="Debian"
    - name: Install nginx on redhat family
      package:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat"
    - name: Start httpd daemon
      service: 
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family=="RedHat"
    - name: Create user serge
      user:
        name: Serge
        comment: Serge Smith
        shell: /bin/bash
    - name: create group
      group:
        name: cloudteam
        state: present
    - name: create index file
      file:
        path: /var/www/html/index.html
        state: touch
      register: file_output
      tags:
        - a
    - name: read data
      debug:
          var: file_output.diff.before.path
    - name: Create directory
      file:
        path: /tmp/os
        state: directory
    
    - name : Copy content to index
      copy:
        dest: file_output.diff.before.path
        content: '<h1>This is created using ansible</h1>'
